### ISSUE TITLE
Error on hover

### ISSUE THREAD

**Issue by mjcumming** [openhab/openhab-vscode#97] opened 2018-06-15 16:06 UTC
When hovering over an item while editing .rules file, I see the error below in the output console of VS Code.

`[Error - 11:02:25 AM] Request textDocument/hover failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603 `

Running openHABian 2.3 on a PI 3+

I do not see anything logged on the openhab logging window.

**Comment by kubawolanin** [comment] 2018-06-16 08:07
Hi @mjcumming 
This is a server-side issue, A duplicate of https://github.com/eclipse/smarthome/issues/4831 to be exact.

**Closed by kubawolanin** 2018-06-16 08:07 UTC
