### ISSUE TITLE
Work with local repository instead of shared folder

### ISSUE THREAD

**Issue by PascalTurbo** [openhab/openhab-vscode#113] opened 2018-11-02 11:12 UTC
After some help from the community I figured out, that the code validation only works when using a shared folder.
So you need a specific development installation (what's hard to build up with different bus systems) or you have to work on your productive environment. 

I think it would be better to support the option to work on a local repository and only use the openhab server vor code validation.

**Comment by Confectrician** [comment] 2018-11-03 18:05
Can you point me to the community thread for a detailed overview?

The conditions for code validation are (or should be):

- Extension is active
(It gets activated when you open any openhab file. For example a `.rules` files)
- Language server enabled
(This is done with within the extension configuration)

When those conditions are true, it shouldn't matter where your configuration files are located.
I have tested this behavior with the current extension version and my configuration files, which i am managing through github.

I am working on a local copy, which then gets pushed to github and pulled afterwards into my production system.
The code validation is working fine, on my local copy.

If it doesn't work in your case with local files, we should check the configuration and the conditions first.

**Comment by Confectrician** [comment] 2018-11-03 18:06
Ah i think it is this one:
https://community.openhab.org/t/vscode-doesnt-validate-my-code/55239/6

I will read through it to get an overview.

**Comment by Confectrician** [comment] 2018-11-03 18:15
Ok now i am up to date.

Please notice that the problem is not really on VsCode side here.
See eclipse/smarthome#6430 for reference.

> I think it would be better to support the option to work on a local repository and only use the openhab server vor code validation.

So this was the case already some time ago and will hopefully be fixed soon in the eclipse smarthome repository again.


Are you fine with closing this issue and do all of the discussion in the eclipse smarthome repo to keep all relevant informations in one place?

**Comment by PascalTurbo** [comment] 2018-11-03 18:15
> Ah i think it is this one:
> https://community.openhab.org/t/vscode-doesnt-validate-my-code/55239/6
> 
> I will read through it to get an overview.

**Comment by Confectrician** [comment] 2018-11-03 18:34
I have testet this behavior and can't confirm that.

This is `local` and the **direct** conf folder structure.
![image](https://user-images.githubusercontent.com/7161177/47955861-71b03400-df9e-11e8-8310-4e29d639f580.png)

This is `remote/share` and the **direct** conf folder structure.
![image](https://user-images.githubusercontent.com/7161177/47955897-031fa600-df9f-11e8-8513-8c90b9672a1a.png)

A am on:

OS: Windows 10
VsCode: 1.28.2
openHAB Extension: 0.4.0 (latest)
openHAB: 2.3.0 Release Build

Please post your setup, so we can find out a difference maybe.

**Comment by PascalTurbo** [comment] 2018-11-04 18:17
I'm on:

OS: MacOS 10.14 Mojave
VSCode: 1.28.2
openHAB Extension: 0.4.0 (latest)
openHAB: 2.3.0 Release Build

So the difference seems to be the OS

**Comment by Confectrician** [comment] 2018-11-05 19:46
Yep that could already be the reason, since the issue in eclipse smarthome also speks from different handling of file paths.

Maybe we should follow up that issue and leave this one open for reference.
From my view this doesn't seem to be unrelated/off topic.

**Comment by Confectrician** [comment] 2019-10-11 14:55
Hey @PascalTurbo,

The related smarthome issue was closed some time ago.
Are you still facing problems?

If not i would then close this issue for now.

**Comment by Confectrician** [comment] 2019-10-26 19:11
No reaction for 15 Days -> Closing now.
If its still unsolved, we can reopen it again.

**Closed by Confectrician** 2019-10-26 19:11 UTC
Labels: question
